"""precisao

Revision ID: 045876ef15d3
Revises: 347f06996264
Create Date: 2023-04-27 20:30:02.666674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045876ef15d3'
down_revision = '347f06996264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raca_pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precisao', sa.Float(), nullable=True))

    with op.batch_alter_table('raca_tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precisao', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raca_tutor', schema=None) as batch_op:
        batch_op.drop_column('precisao')

    with op.batch_alter_table('raca_pet', schema=None) as batch_op:
        batch_op.drop_column('precisao')

    # ### end Alembic commands ###
