"""novas tabelas

Revision ID: 347f06996264
Revises: 5fa5421b0e80
Create Date: 2023-04-27 19:25:07.189049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347f06996264'
down_revision = '5fa5421b0e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raca_pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encontrar_pet_id', sa.Integer(), nullable=False),
    sa.Column('raca', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['encontrar_pet_id'], ['encontrar_pet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raca_tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encontrar_tutor_id', sa.Integer(), nullable=False),
    sa.Column('raca', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['encontrar_tutor_id'], ['encontrar_tutor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encontrar_pet', schema=None) as batch_op:
        batch_op.drop_column('raca')

    with op.batch_alter_table('encontrar_tutor', schema=None) as batch_op:
        batch_op.drop_column('raca')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encontrar_tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raca', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('encontrar_pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raca', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    op.drop_table('raca_tutor')
    op.drop_table('raca_pet')
    # ### end Alembic commands ###
