"""delete-cascade

Revision ID: 5fa5421b0e80
Revises: 24a20cd4fc67
Create Date: 2023-04-26 22:38:29.035021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa5421b0e80'
down_revision = '24a20cd4fc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encontrar_pet_foto', schema=None) as batch_op:
        batch_op.drop_constraint('encontrar_pet_foto_encontrar_pet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'encontrar_pet', ['encontrar_pet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('encontrar_tutor_foto', schema=None) as batch_op:
        batch_op.drop_constraint('encontrar_tutor_foto_encontrar_tutor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'encontrar_tutor', ['encontrar_tutor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encontrar_tutor_foto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('encontrar_tutor_foto_encontrar_tutor_id_fkey', 'encontrar_tutor', ['encontrar_tutor_id'], ['id'])

    with op.batch_alter_table('encontrar_pet_foto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('encontrar_pet_foto_encontrar_pet_id_fkey', 'encontrar_pet', ['encontrar_pet_id'], ['id'])

    # ### end Alembic commands ###
