"""empty message

Revision ID: 6dd5c323ae88
Revises: 
Create Date: 2023-04-09 22:42:39.575762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd5c323ae88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encontrar_pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('tutor_nome', sa.String(length=100), nullable=True),
    sa.Column('tutor_email', sa.String(length=50), nullable=True),
    sa.Column('tutor_telefone', sa.String(length=20), nullable=True),
    sa.Column('raca', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encontrar_pet_foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encontrar_pet_id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['encontrar_pet_id'], ['encontrar_pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encontrar_pet_foto')
    op.drop_table('encontrar_pet')
    # ### end Alembic commands ###
