"""fotos

Revision ID: 76d08083729a
Revises: 045876ef15d3
Create Date: 2023-04-29 14:10:13.712567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d08083729a'
down_revision = '045876ef15d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encontrar_pet_foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('arquivo')

    with op.batch_alter_table('encontrar_tutor_foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('arquivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encontrar_tutor_foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('foto')

    with op.batch_alter_table('encontrar_pet_foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
